version: '3.9'
services:
   fw:
    image: nginx:alpine
    container_name: fw
    hostname: fw
    ports:
      - 8080:8080
#    volumes: 
#      - ./src/app_1:/usr/share/nginx/html
    networks:
     vlan10:
      ipv4_address: 192.168.1.100
    environment:
      VLAN: 10
    networks:
     vlan30:
      ipv4_address: 10.1.1.200
    environment:
      VLAN: 30
    networks:
     externo:
      ipv4_address: 201.10.151.102
    cap_add:
     - NET_ADMIN
    restart: always


    

networks:

   vlan10:
    name: vlan10
    driver: macvlan
    driver_opts:
      parent: eth0.10
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 192.168.1.0/24
          



   vlan30:
    name: vlan30
    driver: ipvlan
    driver_opts:
      parent: eth0.30
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 10.1.1.0/24



   vlan20:
    name: vlan20
    driver: macvlan
    driver_opts:
      parent: eth0.20
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 192.168.2.0/24

   externo:
    name: externo
    driver: bridge
    driver_opts:
      parent: eth0.50
    ipam:
      config:
        - subnet: 201.10.151.100/30
          gateway: 201.10.151.101

 
